-- Mock Data for Live From the Mothership Artist Signups
-- Run this SQL in your Supabase SQL Editor to populate test data
-- This creates realistic sample submissions for testing

-- First, ensure the table exists with proper structure
CREATE TABLE IF NOT EXISTS artist_signups (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    artist_name TEXT NOT NULL,
    artist_type TEXT NOT NULL CHECK (artist_type IN ('solo', 'group')),
    email TEXT NOT NULL,
    phone TEXT,
    location TEXT NOT NULL,
    genres JSONB NOT NULL,
    instagram TEXT,
    twitter TEXT,
    youtube TEXT,
    soundcloud TEXT,
    spotify TEXT,
    bio TEXT NOT NULL,
    terms_agreed BOOLEAN NOT NULL DEFAULT false,
    privacy_agreed BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert mock data (15 realistic artist submissions)
INSERT INTO artist_signups (
    artist_name, artist_type, email, phone, location, genres, 
    instagram, twitter, youtube, soundcloud, spotify, bio, 
    terms_agreed, privacy_agreed, created_at
) VALUES 
(
    'DJ Midnight Flow',
    'solo',
    'midnightflow@gmail.com',
    '+1-404-555-0123',
    'Atlanta, GA',
    '["Hip-Hop", "Electronic"]',
    '@djmidnightflow',
    '@midnight_flow',
    'https://youtube.com/@djmidnightflow',
    'https://soundcloud.com/midnight-flow',
    'https://open.spotify.com/artist/midnight-flow',
    'Been spinning beats in Atlanta for 8 years. My sound blends classic hip-hop with modern electronic elements. Ready to bring the energy to the Mothership!',
    true,
    true,
    NOW() - INTERVAL '2 hours'
),
(
    'The Sonic Rebels',
    'group',
    'sonicrebels@outlook.com',
    '+1-678-555-0456',
    'Decatur, GA',
    '["Rock", "Alternative"]',
    '@thesonicrebels',
    '@sonic_rebels',
    'https://youtube.com/thesonicrebels',
    'https://soundcloud.com/sonic-rebels',
    NULL,
    'Four-piece alternative rock band from Decatur. We write our own music and have been performing together for 3 years. Our sound is influenced by classic rock but with a modern twist.',
    true,
    true,
    NOW() - INTERVAL '4 hours'
),
(
    'Luna Rodriguez',
    'solo',
    'luna.rodriguez.music@gmail.com',
    NULL,
    'Marietta, GA',
    '["R&B", "Pop"]',
    '@lunarodriguezmusic',
    '@luna_r_music',
    'https://youtube.com/@lunarodriguez',
    NULL,
    'https://open.spotify.com/artist/luna-rodriguez',
    'Singer-songwriter with a passion for R&B and pop fusion. I write all my own lyrics and have been performing at local venues for 2 years. Looking forward to this competition!',
    true,
    true,
    NOW() - INTERVAL '6 hours'
),
(
    'Beat Machine Collective',
    'group',
    'beatmachine@protonmail.com',
    '+1-770-555-0789',
    'Roswell, GA',
    '["Hip-Hop", "Jazz"]',
    '@beatmachinecollective',
    '@beatmachine_atl',
    'https://youtube.com/beatmachinecollective',
    'https://soundcloud.com/beat-machine-collective',
    'https://open.spotify.com/artist/beat-machine-collective',
    'Producer collective specializing in jazz-infused hip-hop. We have 5 core members and have produced tracks for several local artists. Ready to create something amazing live!',
    true,
    true,
    NOW() - INTERVAL '8 hours'
),
(
    'Zara Nightfall',
    'solo',
    'zara.nightfall@yahoo.com',
    '+1-404-555-0234',
    'East Point, GA',
    '["Electronic", "Pop"]',
    '@zaranightfall',
    '@zara_nightfall',
    NULL,
    'https://soundcloud.com/zara-nightfall',
    NULL,
    'Electronic pop artist with a dark, atmospheric sound. I produce my own tracks and perform with live instruments. Been in the Atlanta music scene for 4 years.',
    true,
    true,
    NOW() - INTERVAL '10 hours'
),
(
    'The ATL Groove Squad',
    'group',
    'atlgroovesquad@gmail.com',
    '+1-678-555-0567',
    'Buckhead, GA',
    '["R&B", "Hip-Hop"]',
    '@atlgroovesquad',
    '@atl_groove_squad',
    'https://youtube.com/atlgroovesquad',
    'https://soundcloud.com/atl-groove-squad',
    'https://open.spotify.com/artist/atl-groove-squad',
    'Six-member R&B/Hip-Hop group with strong vocal harmonies and original choreography. We have performed at several Atlanta festivals and are excited for this opportunity!',
    true,
    true,
    NOW() - INTERVAL '12 hours'
),
(
    'Marcus "Phoenix" Johnson',
    'solo',
    'phoenix.johnson.music@gmail.com',
    '+1-470-555-0890',
    'College Park, GA',
    '["Hip-Hop"]',
    '@phoenixjohnsonmusic',
    '@phoenix_atl',
    'https://youtube.com/@phoenixjohnson',
    'https://soundcloud.com/phoenix-johnson',
    'https://open.spotify.com/artist/phoenix-johnson',
    'Lyricist and rapper from College Park. My music tells stories about overcoming challenges and rising from adversity. Been writing and performing for 6 years.',
    true,
    true,
    NOW() - INTERVAL '14 hours'
),
(
    'Stellar Harmony',
    'group',
    'stellarharmony.band@gmail.com',
    '+1-404-555-0345',
    'Sandy Springs, GA',
    '["Pop", "Rock"]',
    '@stellarharmonyband',
    '@stellar_harmony',
    'https://youtube.com/stellarharmony',
    NULL,
    'https://open.spotify.com/artist/stellar-harmony',
    'Three-piece pop-rock band with strong female vocals. We write catchy melodies with meaningful lyrics. Our debut EP drops next month!',
    true,
    true,
    NOW() - INTERVAL '16 hours'
),
(
    'DJ Cosmic Ray',
    'solo',
    'dj.cosmicray@hotmail.com',
    '+1-678-555-0678',
    'Kennesaw, GA',
    '["Electronic", "Hip-Hop"]',
    '@djcosmicray',
    '@cosmic_ray_dj',
    'https://youtube.com/@djcosmicray',
    'https://soundcloud.com/dj-cosmic-ray',
    NULL,
    'Electronic music producer and DJ specializing in bass-heavy tracks. I have performed at several clubs in Atlanta and love creating high-energy music.',
    true,
    true,
    NOW() - INTERVAL '18 hours'
),
(
    'The Peach State Poets',
    'group',
    'peachstatepoets@gmail.com',
    '+1-770-555-0456',
    'Smyrna, GA',
    '["Hip-Hop", "Alternative"]',
    '@peachstatepoets',
    '@peach_state_poets',
    'https://youtube.com/peachstatepoets',
    'https://soundcloud.com/peach-state-poets',
    'https://open.spotify.com/artist/peach-state-poets',
    'Four rappers and poets who blend spoken word with hip-hop beats. We focus on social consciousness and community building through our art.',
    true,
    true,
    NOW() - INTERVAL '20 hours'
),
(
    'Skylar Blue',
    'solo',
    'skylar.blue.music@gmail.com',
    NULL,
    'Johns Creek, GA',
    '["Pop", "R&B"]',
    '@skylarbluemusic',
    '@skylar_blue_',
    NULL,
    NULL,
    'https://open.spotify.com/artist/skylar-blue',
    'Singer-songwriter with a contemporary R&B/Pop style. I have been performing at open mics around Atlanta for 2 years and am ready to take it to the next level.',
    true,
    true,
    NOW() - INTERVAL '22 hours'
),
(
    'Bass Drop Collective',
    'group',
    'bassdropcollective@protonmail.com',
    '+1-404-555-0567',
    'Alpharetta, GA',
    '["Electronic", "Hip-Hop"]',
    '@bassdropcollective',
    '@bass_drop_atl',
    'https://youtube.com/bassdropcollective',
    'https://soundcloud.com/bass-drop-collective',
    NULL,
    'Electronic music collective with 3 producers and 2 vocalists. We specialize in trap and dubstep with hip-hop influences. Ready to shake the Mothership!',
    true,
    true,
    NOW() - INTERVAL '1 day'
),
(
    'Jade Williams',
    'solo',
    'jade.williams.artist@outlook.com',
    '+1-678-555-0234',
    'Stone Mountain, GA',
    '["Jazz", "R&B"]',
    '@jadewilliamsmusic',
    '@jade_w_music',
    'https://youtube.com/@jadewilliams',
    NULL,
    'https://open.spotify.com/artist/jade-williams',
    'Jazz vocalist with R&B influences. I have a degree in music performance and have been singing professionally for 5 years. Love improvisation and live performance.',
    true,
    true,
    NOW() - INTERVAL '1 day 2 hours'
),
(
    'The Underground Sound',
    'group',
    'undergroundsound.atl@gmail.com',
    '+1-470-555-0789',
    'East Atlanta, GA',
    '["Rock", "Alternative"]',
    '@undergroundsoundatl',
    '@underground_atl',
    'https://youtube.com/undergroundsound',
    'https://soundcloud.com/underground-sound-atl',
    NULL,
    'Alternative rock band with punk influences. We write politically conscious music and have been part of the Atlanta underground scene for 4 years.',
    true,
    true,
    NOW() - INTERVAL '1 day 4 hours'
),
(
    'DJ Vortex',
    'solo',
    'dj.vortex.atl@gmail.com',
    '+1-404-555-0890',
    'Midtown Atlanta, GA',
    '["Electronic", "Other"]',
    '@djvortexatl',
    '@vortex_dj',
    'https://youtube.com/@djvortex',
    'https://soundcloud.com/dj-vortex-atl',
    'https://open.spotify.com/artist/dj-vortex',
    'Experimental electronic artist pushing the boundaries of genre. I create immersive soundscapes and have performed at several art galleries and underground venues.',
    true,
    true,
    NOW() - INTERVAL '1 day 6 hours'
);

-- Add some additional test entries with different combinations
INSERT INTO artist_signups (
    artist_name, artist_type, email, location, genres, bio, 
    terms_agreed, privacy_agreed, created_at
) VALUES 
(
    'Echo Chamber',
    'group',
    'echochamber.music@gmail.com',
    'Lawrenceville, GA',
    '["Electronic", "Jazz"]',
    'Experimental jazz-electronic fusion group. We blend live instruments with digital production to create unique soundscapes.',
    true,
    true,
    NOW() - INTERVAL '2 days'
),
(
    'Riley Storm',
    'solo',
    'riley.storm.music@yahoo.com',
    'Duluth, GA',
    '["Pop"]',
    'Pop artist with a focus on empowering lyrics and catchy hooks. Been writing songs since I was 12 and ready to share my music with the world.',
    true,
    true,
    NOW() - INTERVAL '2 days 3 hours'
);

-- Query to verify the data was inserted
SELECT 
    artist_name, 
    artist_type, 
    email, 
    location, 
    genres,
    created_at
FROM artist_signups 
ORDER BY created_at DESC;